server:
  port: 8110
spring:
  profiles:
    active: dev
  application:
    name: guli-edu
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/db190805_guli_edu?characterEncoding=utf-8&useSSL=false
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: GuliHikariPool
      maximum-pool-size: 12
      connection-timeout: 60000
      minimum-idle: 10
      idle-timeout: 500000
      max-lifetime: 540000
      connection-test-query: SELECT 1
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:com/atguigu/guli/service/edu/mapper/xml/*.xml
#连接的注册中心
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9110/eureka/ #指定注册中心地址
  instance:
    prefer-ip-address: true
#eureka:
#  instance:
    # 心跳检测检测与续约时间
    # 测试时将值设置设置小些，保证服务关闭后注册中心能及时踢出服务
    # 配置说明
    # lease-renewal-interval-in-seconds 每间隔5s，向服务端发送一次心跳，证明自己依然”存活“，默认 30
    lease-renewal-interval-in-seconds: 5
    # lease-expiration-duration-in-seconds  告诉服务端，如果我10s之内没有给你发心跳，就代表我“死”了，将我踢出掉，默认 90
    lease-expiration-duration-in-seconds: 10
#开启熔断保护：默认false
feign:
  hystrix:
    enabled: true